import {
	IconFileZip,
	IconUser,
	IconSettings,
	IconSearch,
	IconFilter,
	IconMenu2,
	IconX,
	IconLayoutGridAdd,
	IconFileTypeXls,
	IconPlus,
	IconMessageCircleFilled,
	IconUpload,
	IconArrowBack,
	IconEdit,
	IconTrash,
	IconDownload,
	IconThumbUpFilled,
	IconThumbDownFilled,
	IconRefresh,
	IconDeviceFloppy,
	IconChevronRight,
	IconChevronLeft,
	IconFileFilled,
	IconNotes,
	IconLogout,
	IconAlertTriangle,
	IconCircleXFilled,
	IconCircleCheckFilled,
	IconSend,
	IconAlertHexagon,
	IconAddressBook,
	IconReceipt,
	IconNotebook,
	IconClipboardList,
	IconFileAnalytics,
	IconWallet,
	IconTicket,
	IconReceiptRefund,
	IconFileUpload,
	IconFileDescription,
	IconBook2,
	IconUsers,
	IconLogs,
	IconPower,
	IconFileInvoice,
	IconFileDownload,
	IconReport,
	IconCornerUpLeftDouble,
	IconHome,
	IconEyeOff,
	IconEye,
	IconReceiptRupee,
	IconBuildingBank,
	IconFilePercent,
	IconMoneybagMinus,
	IconUserScreen,
	IconFolder,
	IconChevronDown,
	IconFileDatabase,
	IconAnalyze,
	IconChevronUp,
	IconCreditCardRefund,
	IconReceiptTax,
	IconPigMoney,
	IconFileIsr,
	IconUserCircle,
	IconFileDots,
	IconCashRegister,
	IconBellRinging,
	IconList,
	IconSquareCheck,
	IconSquareX,
	IconCircleCheck,
	IconPencil,
	IconCheck,
	IconCalendarEvent,
} from "@tabler/icons-react";

export const Icons = {
	zip: IconFileZip,
	user: IconUser,
	settings: IconSettings,
	search: IconSearch,
	filter: IconFilter,
	menu: IconMenu2,
	x: IconX,
	pencial: IconPencil,
	check: IconCheck,
	cancel: IconX,
	grid: IconLayoutGridAdd,
	excel: IconFileTypeXls,
	plus: IconPlus,
	chat: IconMessageCircleFilled,
	upload: IconUpload,
	back: IconArrowBack,
	edit: IconEdit,
	calendarEvent: IconCalendarEvent,
	delete: IconTrash,
	download: IconDownload,
	thumbup: IconThumbUpFilled,
	thumbdown: IconThumbDownFilled,
	refresh: IconRefresh,
	save: IconDeviceFloppy,
	rightarrow: IconChevronRight,
	leftarrow: IconChevronLeft,
	file: IconFileFilled,
	text: IconNotes,
	logout: IconLogout,
	alert: IconAlertTriangle,
	circlex: IconCircleXFilled,
	circlecheck: IconCircleCheckFilled,
	send: IconSend,
	hexalert: IconAlertHexagon,
	book: IconAddressBook,
	receipt: IconReceipt,
	notebook: IconNotebook,
	clipboard: IconClipboardList,
	status: IconFileAnalytics,
	wallet: IconWallet,
	ticket: IconTicket,
	return: IconReceiptRefund,
	fileupload: IconFileUpload,
	filedescription: IconFileDescription,
	iconbook: IconBook2,
	users: IconUsers,
	logs: IconLogs,
	powericon: IconPower,
	invoice: IconFileInvoice,
	filedownload: IconFileDownload,
	report: IconReport,
	wotback: IconCornerUpLeftDouble,
	home: IconHome,
	eyeoff: IconEyeOff,
	eye: IconEye,
	salary: IconReceiptRupee,
	tcs: IconBuildingBank,
	interest: IconFilePercent,
	withdrawal: IconMoneybagMinus,
	vendor: IconUserScreen,
	folder: IconFolder,
	downarrow: IconChevronDown,
	masterdata: IconFileDatabase,
	reconciliation: IconAnalyze,
	uparrow: IconChevronUp,
	refund: IconCreditCardRefund,
	receiptTax: IconReceiptTax,
	pigMoney: IconPigMoney,
	fileIsr: IconFileIsr,
	userCircle: IconUserCircle,
	fileDots: IconFileDots,
	cashRegister: IconCashRegister,
	bellRinging: IconBellRinging,
	others: IconList,
	squareCheck: IconSquareCheck,
	squareCancel: IconSquareX,
	circleCheck: IconCircleCheck,
};
